/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as PlantaRouteImport } from './routes/planta'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes/$id'
import { Route as ProjetosIndexRouteImport } from './routes/projetos/index'
import { Route as ProjetosIdRouteImport } from './routes/projetos/$id'
import { Route as ProjetosNovoRouteImport } from './routes/projetos/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantaRoute = PlantaRouteImport.update({
  id: '/planta',
  path: '/planta',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/mais': typeof MaisRoute
  '/materiais': typeof MateriaisRoute
  '/orcamentos': typeof OrcamentosRoute
  '/planta': typeof PlantaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/mais': typeof MaisRoute
  '/materiais': typeof MateriaisRoute
  '/orcamentos': typeof OrcamentosRoute
  '/planta': typeof PlantaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/mais': typeof MaisRoute
  '/materiais': typeof MateriaisRoute
  '/orcamentos': typeof OrcamentosRoute
  '/planta': typeof PlantaRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklists'
    | '/configuracoes'
    | '/empresa'
    | '/mais'
    | '/materiais'
    | '/orcamentos'
    | '/planta'
    | '/clientes/$id'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/clientes/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklists'
    | '/configuracoes'
    | '/empresa'
    | '/mais'
    | '/materiais'
    | '/orcamentos'
    | '/planta'
    | '/clientes/$id'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/clientes'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/checklists'
    | '/configuracoes'
    | '/empresa'
    | '/mais'
    | '/materiais'
    | '/orcamentos'
    | '/planta'
    | '/clientes/$id'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/clientes/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmpresaRoute: typeof EmpresaRoute
  MaisRoute: typeof MaisRoute
  MateriaisRoute: typeof MateriaisRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PlantaRoute: typeof PlantaRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planta': {
      id: '/planta'
      path: '/planta'
      fullPath: '/planta'
      preLoaderRoute: typeof PlantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistsRoute: ChecklistsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmpresaRoute: EmpresaRoute,
  MaisRoute: MaisRoute,
  MateriaisRoute: MateriaisRoute,
  OrcamentosRoute: OrcamentosRoute,
  PlantaRoute: PlantaRoute,
  ClientesIdRoute: ClientesIdRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
